[longblack]
title = "롱블랙"
url = "https://www.longblack.co/"
entrySelector = "div[id='main-content']"
titleSelector = "h2.today-note-title"
linkSelector = "a"
contentSelector = "p.today-note-desc"
waitUntil = "networkidle"
onFail = "stale"
