[longblack]
title = "롱블랙"
url = "https://www.longblack.co/"
entrySelector = "div[id='main-today-note']"
titleSelector = "h2.today-note-title"
linkSelector = "a"
contentSelector = "p.today-note-desc"
imageSelector = "div.bg-img.ratio-4-3"
waitUntil = "networkidle"