[default]
timeout = 180

[longblack]
title = "롱블랙"
url = "https://www.longblack.co/"
entrySelector = "div[id='main-content']"
titleSelector = "h2.today-note-title"
linkSelector = "a"
contentSelector = "p.today-note-desc"
waitForSelector = "div[id='main-content']"
onFail = "stale"
